### ISSUE TITLE
incorrect link

### ISSUE THREAD

**Issue by huiqiang-sun** [Yubel426/NeRF-3DGS-at-CVPR-2024#1]
Hi, thanks for your great project. 
I am the author of the paper 'DyBluRF: Dynamic Neural Radiance Fields from Blurry Monocular Video', and I'm glad you've collected our work. I happened to notice that the website link of our paper directs to the wrong project page. Our paper's homepage is https://huiqiang-sun.github.io/dyblurf/. We would appreciate if you could make the correction. The figure below can prove that our paper was accepted by CVPR2024.
Sincerely thank you for collecting our papers.
![3201e390d68599fe35a6d11a78c841b](https://github.com/Yubel426/NeRF-3DGS-at-CVPR-2024/assets/137331394/93b29afc-deb4-4e42-afa0-84a9be6f6000)

**Comment by Yubel426** [comment]
I sincerely apologize for the oversight that led to the error. I have now rectified it and thank you for bringing this to my attention.

**Comment by huiqiang-sun** [comment]
Thank you very much!!
